#!/usr/bin/env zsh

NEW_PIC="$1"
NUM_DESKTOPS="$2"

if [ -z "$NEW_PIC" ]; then
  echo "Usage: $0 image [desktopCount]"
  exit 1
fi

if [ ! -f "$NEW_PIC" ]; then
    echo "Error: File $NEW_PIC does not exist"
    exit 1
fi

if [ -z "$NUM_DESKTOPS" ]; then
  NUM_DESKTOPS=5
  echo "Defaulted number of desktops to $NUM_DESKTOPS"
fi

# Go to leftmost desktop
function go_left() {
  for i in {1..$NUM_DESKTOPS}; do
    osascript -e 'tell application "System Events" to key code 123 using {control down}'
  done
}
go_left

# Set image for each desktop
for i in {1..$NUM_DESKTOPS}; do
  osascript -e 'on run picture_file' \
            -e '  tell application "System Events"' \
            -e '    tell every desktop' \
            -e '      set picture to picture_file' \
            -e '    end tell' \
            -e '    key code 124 using {control down}' \
            -e '    delay 0.5' \
            -e '  end tell' \
            -e 'end run' \
            "$NEW_PIC"
done
go_left